
version: 2

sources:
    - name: staging
      #For bigquery:
      database: calcium-petal-376805

      # For postgres:
      #database: production

      schema: taxi_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
